[manifest]
version = "1.0.0"
dump_lua = true
priority = 10

[[patches]]
[patches.pattern]
target = 'functions/UI_definitions.lua'
pattern = '''if (v.type == 'Base' or v.type == 'Enhanced') and G.GAME.used_vouchers["v_illusion"] and pseudorandom(pseudoseed('illusion')) > 0.8 then'''
position = 'before'
match_indent = true
payload = '''if (v.type == 'Base' or v.type == 'Enhanced') and G.GAME.used_vouchers["v_illusion"] and pseudorandom(pseudoseed('illusion')) > 0.8 then
    local seal_poll = pseudorandom(pseudoseed('illusion'))
    local seal = {}
    local all_seals = G.P_CENTER_POOLS.Seal

    for i=1, #all_seals do
        local match_prob = 1/#all_seals

        if seal_poll > 1 - (match_prob * i) then
            seal = all_seals[i]
            break
        end
    end

    if next(seal) then
        card:set_seal(seal.key, true)
    end
end'''
